export { default as HomeHeader } from './Header'
export { default as HomeContent } from './Content'
export { default as HomeFooter } from './Footer'
export { default as HomeAside } from './Aside'
// export { default as TagsView } from './TagsView'
